---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:

  - name: nexus3-oss-ubuntu-18.04
    hostname: nexus3-oss-ubuntu-18.04
    image: thoteam/molecule_apache_openjdk8:ubuntu_18.04
    command: lib/systemd/systemd
    pull: true
    pre_build_image: true
    privileged: true
    published_ports:
      - 8094:443
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/.nexus-downloads:/nexus-downloads"

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible

scenario:
  check_sequence:
    - destroy
    - create
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra
