---
- name: Removing (potential) previously declared Groovy script {{ (item.path | basename | splitext)[0] }}
  uri:
    url: "{{ nexus_api_scheme }}://{{ nexus_api_hostname }}:{{ nexus_api_port }}\
      {{ nexus_api_context_path }}{{ nexus_rest_api_endpoint }}/{{ (item.path | basename | splitext)[0] }}"
    user: 'admin'
    password: "{{ current_nexus_admin_password }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204,404
    validate_certs: "{{ nexus_api_validate_certs }}"
  delegate_to: localhost

- name: Declaring Groovy script {{ (item.path | basename | splitext)[0] }}
  uri:
    url: "{{ nexus_api_scheme }}://{{ nexus_api_hostname }}:{{ nexus_api_port }}\
      {{ nexus_api_context_path }}{{ nexus_rest_api_endpoint }}"
    user: 'admin'
    password: "{{ current_nexus_admin_password }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    validate_certs: "{{ nexus_api_validate_certs }}"
    body:
      name: "{{ (item.path | basename | splitext)[0] }}"
      type: 'groovy'
      content: "{{ lookup('file', item.path ) }}"
  delegate_to: localhost