---
# This file contains all requirements and deprecation checks
# that can be run before the role starts.

# @requirement: jmespath module must be installed on ansible host
# @version: 2.4.0
- name: Check presence of jmespath python module on ansible host
  block:
    - name: Try to use jmespath on a test var
      ansible.builtin.set_fact:
        voidvar: "{{ [] | json_query('[]') }}"
  rescue:
    - name: Print message about jmespath
      ansible.builtin.debug:
        msg:
          - Since version 2.4.0, this role uses the json_query filter
          - which requires the jmespath python module on the host running ansible.
          - Please install jmespath (i.e. `pip install jmespath`) on your ansible host.

    - name: Fail on jmespath missing
      ansible.builtin.fail:
        msg: Install jmespath. See debug message above

# @deprecated: nexus_package must not exists
# @version: 2.2.0
- name: Broken compatibility => nexus_package is now dynamically calculated
  ansible.builtin.fail:
    msg: >-
      You have set the variable nexus_package in your playbook.
      Starting from version 2.2.0 of this role, this is not compatible
      with the new nexus latest version detection feature and is not
      supported anymore. Please use the nexus_version variable only.
  when: nexus_package is defined

# @deprecated: purge was refactored to nexus_purge
# @version: 2.2.3
- name: Broken compatibility => purge var moved to nexus_purge
  ansible.builtin.fail:
    msg: >-
      You have set the purge variable to reset nexus.
      Starting from version 2.2.3 of this role, this variable
      has been renamed nexus_purge. Please fix the var name accordingly
      on you command line call.
  when: purge is defined

# @deprecated: public_hostname was renamed to nexus_public_hostname
# @version: 2.3.0
- name: Variable refactoring - public_hostname is now nexus_public_hostname
  ansible.builtin.fail:
    msg: >-
      Version 2.3.0 of this role introduced a variable name change: public_hostname was renamed to
      nexus_public_hostname. We have detected that public_hostname is set in your vars ({{ public_hostname }})
      and is different from nexus_public_hostname which still has its default value ({{ nexus_public_hostname }}).
      Fix this by setting a correct value for nexus_public_hostname and remove public_hostname if
      possible.
  when: >-
    public_hostname | default('') | length > 0
    and
    public_hostname != nexus_public_hostname
    and
    nexus_public_hostname == 'nexus.vm'

# @deprecated: remote_url is the variable to configure a proxy repo. proxy_url is not supported
# anymore to configure docker proxy repos
# @version: 2.4.0
- name: "Coding standard: proxy_url is not supported anymore for docker proxy repos"
  ansible.builtin.fail:
    msg: >-
      proxy_url used to be the variable to configure docker proxy repositories in nexus3-oss role. Since version 2.3.0,
      all repository configuration use the same standard var remote_url. Please review your configurations
      in nexus_repos_docker_proxy and rename the variable accordingly.
  when:
    - nexus_repos_docker_proxy | length > 0
    - nexus_repos_docker_proxy | json_query('[?proxy_url]') | list | length > 0

# @requirement: new internal var _nexus_repos_global_List must be undefined
# @version: 2.4.0
- name: Make sure our internal var for repos is unset
  when: _nexus_repos_global_list is defined
  block:
    - name: Print debug message about our internal var
      vars:
        error_msg: |-
          _nexus_repos_global_list is set somewhere in your playbook/inventory.
          This is an internal var that must be unset when the role starts executing.
          Please unset _nexus_repos_global_list from your playbook/inventory
      ansible.builtin.debug:
        msg: "{{ error_msg.split('\n') }}"

    - name: Fail as we cannot run correctly with internal var set
      ansible.builtin.fail:
        msg: Unset _nexus_repos_global_list. See debug message above

# @requirement: new variable nexus_custom_jvm_setting must be a list
# and must not contain other memory settings
# @version: 2.4.16
- name: Make sure nexus_custom_jvm_settings follow our contraints
  vars:
    options: "{{ nexus_custom_jvm_settings | d([]) }}"
    option_blacklist:
      - Xms
      - Xmx
      - XX:MaxDirectMemorySize=
    option_blacklist_regex: -({{ option_blacklist | map('regex_escape') | join('|') }})
  ansible.builtin.assert:
    that:
      - options | type_debug == 'list'
      - options | select('match', option_blacklist_regex) | list | length == 0
    quiet: true
    fail_msg:
      - nexus_custom_jvm_settings must be list
      - and cannot contain any settings related to memory
      - (-{{ option_blacklist | join(', -') }})
