---
# This file contains all requirements and deprecation checks
# that can be run before the role starts.

# @requirement: jmespath module must be installe on ansible host
# @version: 2.4.0
- name: Check presence of jmespath python module on ansible host
  block:
    - name: Try to use jmespath on a test var
      set_fact:
        voidvar: "{{ [] | json_query('[]') }}"
  rescue:
    - name: Print message about jmespath
      vars:
        error_msg: |-
          Since version 2.4.0, this role uses the  json_query filter which requires
          the presense of the python module jmespath on the host running ansible.
          Please install jmespath (i.e. pip install jmespath) on your ansible host.
      debug:
        msg: "{{ error_msg.split('\n') }}"

    - name: fail
      fail:
        msg: "Install jmespath. See debug message above"

# @deprecated: nexus_package must not exists
# @version: 2.2.0
- name: Broken compatibility => nexus_package is now dynamically calculated
  fail:
    msg: >-
      You have set the variable nexus_package in your playbook.
      Starting from version 2.2.0 of this role, this is not compatible
      with the new nexus latest version detection feature and is not
      supported anymore. Please use the nexus_version variable only.
  when: nexus_package is defined

# @deprecated: purge was refactored to nexus_purge
# @version: 2.2.3
- name: Broken compatibility => purge var moved to nexus_purge
  fail:
    msg: >-
      You have set the purge variable to reset nexus.
      Starting from version 2.2.3 of this role, this variable
      has been renamed nexus_purge. Please fix the var name accordingly
      on you command line call.
  when: purge is defined

# @deprecated: public_hostname was renamed to nexus_public_hostname
# @version: 2.3.0
- name: Variable refactoring - public_hostname is now nexus_public_hostname
  fail:
    msg: >-
      Version 2.3.0 of this role introduced a variable name change: public_hostname was renamed to
      nexus_public_hostname. We have detected that public_hostname is set in your vars ({{ public_hostname }})
      and is different from nexus_public_hostname which still has its default value ({{ nexus_public_hostname }}).
      Fix this by setting a correct value for nexus_public_hostname and remove public_hostname if
      possible.
  when: >-
    public_hosname | default('') | length > 0
    and
    public_hostname != nexus_public_hostname
    and
    nexus_public_hostname == 'nexus.vm'

# @deprecated: remote_url is the variable to configure a proxy repo. proxy_url is not supported
# anymore to configure docker proxy repos
# @version: 2.4.0
- name: "Coding standard: proxy_url is not supported anymore for docker proxy repos"
  fail:
    msg: >-
      proxy_url used to be the variable to configure docker proxy repositories in nexus3-oss role. Since version 2.3.0,
      all repository configuration use the same standard var remote_url. Please review your configurations
      in nexus_repos_docker_proxy and rename the variable accordingly.
  when: >-
    nexus_repos_docker_proxy
    | json_query('[?proxy_url]')
    | list
    | length > 0

# @requirement: new internal var _nexus_repos_global_List must be undefined
# @version: 2.4.0
- name: "Make sure our internal var for repos is unset"
  when: _nexus_repos_global_list is defined
  block:
    - name: Print debug message about our internal var
      vars:
        error_msg: |-
          _nexus_repos_global_list is set somewhere in your playbook/inventory.
          This is an internal var that must be unset when the role starts executing.
          Please unset _nexus_repos_global_list from your playbook/inventory
      debug:
        msg: "{{ error_msg.split('\n') }}"

    - name: Fail as we cannot run correctly with internal var set
      fail:
        msg: "Unset _nexus_repos_global_list. See debug message above"
