---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"

  tasks:
    - name: Destroy molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: "{{ item.force_kill | default(True) }}"
      with_items: "{{ molecule_yml.platforms }}"
