---

httpd_setup_enable: true
httpd_copy_ssl_files: false
httpd_ssl_cert_file_location: "{{ default_cert }}"
httpd_ssl_cert_key_location: "{{ default_key }}"
public_hostname: localhost

nexus_backup_configure: true

nexus_delete_default_repos: true
nexus_delete_default_blobstore: true

nexus_blob_split: true

nexus_config_pypi: true
nexus_config_docker: true
nexus_config_raw: true
nexus_config_rubygems: true
nexus_config_bower: true
nexus_config_npm: true
nexus_config_nuget: true
nexus_config_gitlfs: true
nexus_config_yum: true

nexus_anonymous_access: true

nexus_audit_enabled: true

nexus_rut_auth_realm: false
nexus_rut_auth_header: "CUSTOM_RUT_HEADER"

nexus_repos_npm_hosted: []
nexus_repos_npm_group:
  - name: npm-public
    member_repos:
      - npm-registry
nexus_repos_npm_proxy:
  - name: npm-registry
    remote_url: https://registry.npmjs.org/
    negative_cache_enabled: false

nexus_repos_yum_hosted:
  - name: private_yum_centos_7
    repodata_depth: 1
nexus_repos_yum_proxy:
  - name: epel_centos_7_x86_64
    remote_url: http://download.fedoraproject.org/pub/epel/7/x86_64
    maximum_component_age: -1
    maximum_metadata_age: -1
    negative_cache_ttl: 60
nexus_repos_yum_group:
  - name: yum_all
    member_repos:
      - private_yum_centos_7
      - epel_centos_7_x86_64

nexus_scheduled_tasks:
  #  Example task to purge maven snapshots
  - name: Purge-maven-snapshots
    cron: '0 50 23 * * ?'
    typeId: repository.maven.remove-snapshots
    task_alert_email: alerts@example.org  # optional
    taskProperties:
      repositoryName: "*"
      minimumRetained: "2"
      snapshotRetentionDays: "2"
      gracePeriodInDays: "2"
    booleanTaskProperties:
      removeIfReleased: true

nexus_local_users:
  - username: jenkins
    first_name: Jenkins
    last_name: CI
    email: support@company.com
    password: "s3cr3t"
    roles:
      - developers
  - username: olduser  # make sure this old account is removed
    state: absent

nexus_privileges:
  - name: wildcard1
    type: wildcard
    description: first wilcard
    pattern: nexus:repository-view:yum:*
  - name: some_application
    type: application
    description: some nexus configuration
    domain: some_nexus_domain
    actions:
      - some action
  - name: script1
    type: script
    description: first script
    script_name: the_script_name
    actions:
      - some actions