---
- name: "Prepare poststep 1/2: download nexus package locally"
  hosts: localhost
  vars:
    molecule_project_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"

  tasks:

    - name: include variables from tested playbook
      include_vars:
        file: "{{ molecule_project_dir }}/defaults/main.yml"

    - name: Make sure we have a dir in molecule base path for nexus package download
      # This one should exist from git checkout and is shared accross scenarios
      file:
        path: "{{ molecule_project_dir }}/molecule/.nexus-downloads"
        state: directory

    - name: Get link to current nexus version
      uri:
        url: "{{ nexus_download_url }}/latest-unix.tar.gz"
        method: CONNECT
        status_code: 302
      register: nexus_latest_uri_call

    - name: Get the current nexus version
      get_url:
        url: "{{ nexus_latest_uri_call.location }}"
        dest: "{{ molecule_project_dir }}/molecule/.nexus-downloads\
          /{{ nexus_latest_uri_call.location | urlsplit('path') | basename }}"
        force: no


- name: "Prepare posttep 2/2: sync nexus package to instances"
  hosts: nexus
  vars:
    molecule_project_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
  tasks:

    - name: Copy nexus package(s) to default location into images
      synchronize:
        src: "{{ molecule_project_dir }}/molecule/.nexus-downloads/"
        dest: "/tmp/"
        checksum: yes
        times: no
        perms: no
