---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint:
  name: yamllint

platforms:

  - name: nexus3-oss-default
    hostname: nexus3-oss-default
    image: thoteam/molecule_apache_openjdk8:centos7
    command: /usr/sbin/init
    pull: true
    pre_build_image: true
    privileged: true
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - lint

verifier:
  name: testinfra
  lint:
    name: flake8
