---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:

  - name: nexus3-oss-default
    hostname: nexus3-oss-default
    image: thoteam/molecule_apache_openjdk8:centos7
    command: /usr/sbin/init
    pull: true
    pre_build_image: true
    privileged: true
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/.nexus-downloads:/nexus-downloads"

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible

scenario:
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - lint

verifier:
  name: testinfra
