---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint:
  name: yamllint

platforms:

  - name: nexus3-oss-debian-jessie
    hostname: nexus3-oss-debian-jessie
    image: thoteam/ansible-debian_jessie-apache-java:latest
    command: lib/systemd/systemd
    pull: true
    pre_build_image: true
    privileged: true
    published_ports:
      - 8091:443
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default-debian_jessie
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
