---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker
  safe_files:
    - nexus-downloads

platforms:
  - name: nexus3-oss-ubuntu-22.04
    hostname: nexus3-oss-ubuntu-22.04
    image: thoteam/molecule_apache_openjdk8:ubuntu_22.04
    command: lib/systemd/systemd
    pull: true
    pre_build_image: true
    privileged: true
    published_ports:
      - 8095:443
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/.nexus-downloads:/nexus-downloads

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible

scenario:
  check_sequence:
    - destroy
    - create
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra

role_name_check: 2
