---
- name: Prepare
  hosts: nexus
  become: true
  tasks:
    - name: Install needed dependencies for role testing (redhat)
      yum:
        name:
          - java-1.8.0-openjdk-headless
          - httpd
          - mod_ssl
          - rsync
        state: present
      when: ansible_os_family == 'RedHat'

    - block:
        - name: Install needed dependencies for role testing (debian/ubuntu)
          apt:
            name:
              - apache2
              - openjdk-8-jre-headless
              - rsync
            state: present
            update_cache: true

        - name: Enable needed apache modules
          shell: a2enmod ssl rewrite proxy proxy_http headers

      when: ansible_os_family == 'Debian'

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

- import_playbook: "../sync-nexus-package.yml"
